<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['code' => 'AF', 'dial_code' => 93, 'name' => 'Afghanistan', 'status' => true],
            ['code' => 'AX', 'dial_code' => 358, 'name' => 'Åland Islands', 'status' => true],
            ['code' => 'AL', 'dial_code' => 355, 'name' => 'Albania', 'status' => true],
            ['code' => 'DZ', 'dial_code' => 213, 'name' => 'Algeria', 'status' => true],
            ['code' => 'AS', 'dial_code' => 1684, 'name' => 'American Samoa', 'status' => true],
            ['code' => 'VI', 'dial_code' => 1340, 'name' => 'Virgin Islands (U.S.)', 'status' => true],
            ['code' => 'AD', 'dial_code' => 376, 'name' => 'Andorra', 'status' => true],
            ['code' => 'AO', 'dial_code' => 244, 'name' => 'Angola', 'status' => true],
            ['code' => 'AI', 'dial_code' => 1264, 'name' => 'Anguilla', 'status' => true],
            ['code' => 'AQ', 'dial_code' => 672, 'name' => 'Antarctica', 'status' => true],
            ['code' => 'AG', 'dial_code' => 1268, 'name' => 'Antigua and Barbuda', 'status' => true],
            ['code' => 'AR', 'dial_code' => 54, 'name' => 'Argentina', 'status' => true],
            ['code' => 'AM', 'dial_code' => 374, 'name' => 'Armenia', 'status' => true],
            ['code' => 'AW', 'dial_code' => 297, 'name' => 'Aruba', 'status' => true],
            ['code' => 'AU', 'dial_code' => 61, 'name' => 'Australia', 'status' => true],
            ['code' => 'AZ', 'dial_code' => 994, 'name' => 'Azerbaijan', 'status' => true],
            ['code' => 'BS', 'dial_code' => 1242, 'name' => 'Bahamas (the)', 'status' => true],
            ['code' => 'BH', 'dial_code' => 973, 'name' => 'Bahrain', 'status' => true],
            ['code' => 'BD', 'dial_code' => 880, 'name' => 'Bangladesh', 'status' => true],
            ['code' => 'BB', 'dial_code' => 1246, 'name' => 'Barbados', 'status' => true],
            ['code' => 'BE', 'dial_code' => 32, 'name' => 'Belgium', 'status' => true],
            ['code' => 'BZ', 'dial_code' => 501, 'name' => 'Belize', 'status' => true],
            ['code' => 'BY', 'dial_code' => 375, 'name' => 'Belarus', 'status' => true],
            ['code' => 'BJ', 'dial_code' => 229, 'name' => 'Benin', 'status' => true],
            ['code' => 'BM', 'dial_code' => 1441, 'name' => 'Bermuda', 'status' => true],
            ['code' => 'BT', 'dial_code' => 975, 'name' => 'Bhutan', 'status' => true],
            ['code' => 'BO', 'dial_code' => 591, 'name' => 'Bolivia', 'status' => true],
            ['code' => 'BQ', 'dial_code' => 599, 'name' => 'Bonaire', 'status' => true],
            ['code' => 'BA', 'dial_code' => 387, 'name' => 'Bosnia and Herzegovina', 'status' => true],
            ['code' => 'BW', 'dial_code' => 267, 'name' => 'Botswana', 'status' => true],
            ['code' => 'BV', 'dial_code' => 47, 'name' => 'Bouvet Island', 'status' => true],
            ['code' => 'BR', 'dial_code' => 55, 'name' => 'Brazil', 'status' => true],
            ['code' => 'IO', 'dial_code' => 246, 'name' => 'British Indian Ocean Territory (the)', 'status' => true],
            ['code' => 'VG', 'dial_code' => 1284, 'name' => 'Virgin Islands (British)', 'status' => true],
            ['code' => 'BN', 'dial_code' => 673, 'name' => 'Brunei Darussalam', 'status' => true],
            ['code' => 'BG', 'dial_code' => 359, 'name' => 'Bulgaria', 'status' => true],
            ['code' => 'BF', 'dial_code' => 226, 'name' => 'Burkina Faso', 'status' => true],
            ['code' => 'BI', 'dial_code' => 257, 'name' => 'Burundi', 'status' => true],
            ['code' => 'KH', 'dial_code' => 855, 'name' => 'Cambodia', 'status' => true],
            ['code' => 'CM', 'dial_code' => 237, 'name' => 'Cameroon', 'status' => true],
            ['code' => 'CA', 'dial_code' => 1, 'name' => 'Canada', 'status' => true],
            ['code' => 'CV', 'dial_code' => 238, 'name' => 'Cabo Verde', 'status' => true],
            ['code' => 'KY', 'dial_code' => 1345, 'name' => 'Cayman Islands', 'status' => true],
            ['code' => 'CF', 'dial_code' => 236, 'name' => 'Central African Republic', 'status' => true],
            ['code' => 'TD', 'dial_code' => 235, 'name' => 'Chad', 'status' => true],
            ['code' => 'CL', 'dial_code' => 56, 'name' => 'Chile', 'status' => true],
            ['code' => 'CN', 'dial_code' => 86, 'name' => 'China', 'status' => true],
            ['code' => 'CX', 'dial_code' => 61, 'name' => 'Christmas Island', 'status' => true],
            ['code' => 'CC', 'dial_code' => 61, 'name' => 'Cocos (Keeling) Islands', 'status' => true],
            ['code' => 'CO', 'dial_code' => 57, 'name' => 'Colombia', 'status' => true],
            ['code' => 'KM', 'dial_code' => 269, 'name' => 'Comoros', 'status' => true],
            ['code' => 'CG', 'dial_code' => 242, 'name' => 'Congo', 'status' => true],
            ['code' => 'CD', 'dial_code' => 243, 'name' => 'Congo, Democratic Republic of the', 'status' => true],
            ['code' => 'CK', 'dial_code' => 682, 'name' => 'Cook Islands', 'status' => true],
            ['code' => 'CR', 'dial_code' => 506, 'name' => 'Costa Rica', 'status' => true],
            ['code' => 'HR', 'dial_code' => 385, 'name' => 'Croatia', 'status' => true],
            ['code' => 'CU', 'dial_code' => 53, 'name' => 'Cuba', 'status' => true],
            ['code' => 'CW', 'dial_code' => 599, 'name' => 'Curaçao', 'status' => true],
            ['code' => 'CY', 'dial_code' => 357, 'name' => 'Cyprus', 'status' => true],
            ['code' => 'CZ', 'dial_code' => 420, 'name' => 'Czechia', 'status' => true],
            ['code' => 'DK', 'dial_code' => 45, 'name' => 'Denmark', 'status' => true],
            ['code' => 'DJ', 'dial_code' => 253, 'name' => 'Djibouti', 'status' => true],
            ['code' => 'DM', 'dial_code' => 1767, 'name' => 'Dominica', 'status' => true],
            ['code' => 'DO', 'dial_code' => 1809, 'name' => 'Dominican Republic', 'status' => true],
            ['code' => 'EC', 'dial_code' => 593, 'name' => 'Ecuador', 'status' => true],
            ['code' => 'EG', 'dial_code' => 20, 'name' => 'Egypt', 'status' => true],
            ['code' => 'SV', 'dial_code' => 503, 'name' => 'El Salvador', 'status' => true],
            ['code' => 'GQ', 'dial_code' => 240, 'name' => 'Equatorial Guinea', 'status' => true],
            ['code' => 'ER', 'dial_code' => 291, 'name' => 'Eritrea', 'status' => true],
            ['code' => 'EE', 'dial_code' => 372, 'name' => 'Estonia', 'status' => true],
            ['code' => 'SZ', 'dial_code' => 268, 'name' => 'Eswatini', 'status' => true],
            ['code' => 'ET', 'dial_code' => 251, 'name' => 'Ethiopia', 'status' => true],
            ['code' => 'FK', 'dial_code' => 500, 'name' => 'Falkland Islands (Malvinas)', 'status' => true],
            ['code' => 'FO', 'dial_code' => 298, 'name' => 'Faroe Islands', 'status' => true],
            ['code' => 'FJ', 'dial_code' => 679, 'name' => 'Fiji', 'status' => true],
            ['code' => 'FI', 'dial_code' => 358, 'name' => 'Finland', 'status' => true],
            ['code' => 'FR', 'dial_code' => 33, 'name' => 'France', 'status' => true],
            ['code' => 'GF', 'dial_code' => 594, 'name' => 'French Guiana', 'status' => true],
            ['code' => 'PF', 'dial_code' => 689, 'name' => 'French Polynesia', 'status' => true],
            ['code' => 'TF', 'dial_code' => 262, 'name' => 'French Southern Territories', 'status' => true],
            ['code' => 'GA', 'dial_code' => 241, 'name' => 'Gabon', 'status' => true],
            ['code' => 'GM', 'dial_code' => 220, 'name' => 'Gambia', 'status' => true],
            ['code' => 'GE', 'dial_code' => 995, 'name' => 'Georgia', 'status' => true],
            ['code' => 'DE', 'dial_code' => 49, 'name' => 'Germany', 'status' => true],
            ['code' => 'GH', 'dial_code' => 233, 'name' => 'Ghana', 'status' => true],
            ['code' => 'GI', 'dial_code' => 350, 'name' => 'Gibraltar', 'status' => true],
            ['code' => 'GR', 'dial_code' => 30, 'name' => 'Greece', 'status' => true],
            ['code' => 'GL', 'dial_code' => 299, 'name' => 'Greenland', 'status' => true],
            ['code' => 'GD', 'dial_code' => 1473, 'name' => 'Grenada', 'status' => true],
            ['code' => 'GP', 'dial_code' => 590, 'name' => 'Guadeloupe', 'status' => true],
            ['code' => 'GU', 'dial_code' => 1671, 'name' => 'Guam', 'status' => true],
            ['code' => 'GT', 'dial_code' => 502, 'name' => 'Guatemala', 'status' => true],
            ['code' => 'GG', 'dial_code' => 44, 'name' => 'Guernsey', 'status' => true],
            ['code' => 'GN', 'dial_code' => 224, 'name' => 'Guinea', 'status' => true],
            ['code' => 'GW', 'dial_code' => 245, 'name' => 'Guinea-Bissau', 'status' => true],
            ['code' => 'GY', 'dial_code' => 592, 'name' => 'Guyana', 'status' => true],
            ['code' => 'HT', 'dial_code' => 509, 'name' => 'Haiti', 'status' => true],
            ['code' => 'HM', 'dial_code' => 672, 'name' => 'Heard Island and McDonald Islands', 'status' => true],
            ['code' => 'VA', 'dial_code' => 379, 'name' => 'Holy See', 'status' => true],
            ['code' => 'HN', 'dial_code' => 504, 'name' => 'Honduras', 'status' => true],
            ['code' => 'HK', 'dial_code' => 852, 'name' => 'Hong Kong', 'status' => true],
            ['code' => 'HU', 'dial_code' => 36, 'name' => 'Hungary', 'status' => true],
            ['code' => 'IS', 'dial_code' => 354, 'name' => 'Iceland', 'status' => true],
            ['code' => 'IN', 'dial_code' => 91, 'name' => 'India', 'status' => true],
            ['code' => 'ID', 'dial_code' => 62, 'name' => 'Indonesia', 'status' => true],
            ['code' => 'IR', 'dial_code' => 98, 'name' => 'Iran', 'status' => true],
            ['code' => 'IQ', 'dial_code' => 964, 'name' => 'Iraq', 'status' => true],
            ['code' => 'IE', 'dial_code' => 353, 'name' => 'Ireland', 'status' => true],
            ['code' => 'IM', 'dial_code' => 44, 'name' => 'Isle of Man', 'status' => true],
            ['code' => 'IL', 'dial_code' => 972, 'name' => 'Israel', 'status' => true],
            ['code' => 'IT', 'dial_code' => 39, 'name' => 'Italy', 'status' => true],
            ['code' => 'JM', 'dial_code' => 1876, 'name' => 'Jamaica', 'status' => true],
            ['code' => 'JP', 'dial_code' => 81, 'name' => 'Japan', 'status' => true],
            ['code' => 'JE', 'dial_code' => 44, 'name' => 'Jersey', 'status' => true],
            ['code' => 'JO', 'dial_code' => 962, 'name' => 'Jordan', 'status' => true],
            ['code' => 'KZ', 'dial_code' => 7, 'name' => 'Kazakhstan', 'status' => true],
            ['code' => 'KE', 'dial_code' => 254, 'name' => 'Kenya', 'status' => true],
            ['code' => 'KI', 'dial_code' => 686, 'name' => 'Kiribati', 'status' => true],
            ['code' => 'KP', 'dial_code' => 850, 'name' => "Korea, Democratic People's Republic of", 'status' => true],
            ['code' => 'KR', 'dial_code' => 82, 'name' => 'Korea, Republic of', 'status' => true],
            ['code' => 'KW', 'dial_code' => 965, 'name' => 'Kuwait', 'status' => true],
            ['code' => 'KG', 'dial_code' => 996, 'name' => 'Kyrgyzstan', 'status' => true],
            ['code' => 'LA', 'dial_code' => 856, 'name' => "Lao People's Democratic Republic", 'status' => true],
            ['code' => 'LV', 'dial_code' => 371, 'name' => 'Latvia', 'status' => true],
            ['code' => 'LB', 'dial_code' => 961, 'name' => 'Lebanon', 'status' => true],
            ['code' => 'LS', 'dial_code' => 266, 'name' => 'Lesotho', 'status' => true],
            ['code' => 'LR', 'dial_code' => 231, 'name' => 'Liberia', 'status' => true],
            ['code' => 'LY', 'dial_code' => 218, 'name' => 'Libya', 'status' => true],
            ['code' => 'LI', 'dial_code' => 423, 'name' => 'Liechtenstein', 'status' => true],
            ['code' => 'LT', 'dial_code' => 370, 'name' => 'Lithuania', 'status' => true],
            ['code' => 'LU', 'dial_code' => 352, 'name' => 'Luxembourg', 'status' => true],
            ['code' => 'MO', 'dial_code' => 853, 'name' => 'Macao', 'status' => true],
            ['code' => 'MG', 'dial_code' => 261, 'name' => 'Madagascar', 'status' => true],
            ['code' => 'MW', 'dial_code' => 265, 'name' => 'Malawi', 'status' => true],
            ['code' => 'MY', 'dial_code' => 60, 'name' => 'Malaysia', 'status' => true],
            ['code' => 'MV', 'dial_code' => 960, 'name' => 'Maldives', 'status' => true],
            ['code' => 'ML', 'dial_code' => 223, 'name' => 'Mali', 'status' => true],
            ['code' => 'MT', 'dial_code' => 356, 'name' => 'Malta', 'status' => true],
            ['code' => 'MH', 'dial_code' => 692, 'name' => 'Marshall Islands', 'status' => true],
            ['code' => 'MQ', 'dial_code' => 596, 'name' => 'Martinique', 'status' => true],
            ['code' => 'MR', 'dial_code' => 222, 'name' => 'Mauritania', 'status' => true],
            ['code' => 'MU', 'dial_code' => 230, 'name' => 'Mauritius', 'status' => true],
            ['code' => 'YT', 'dial_code' => 262, 'name' => 'Mayotte', 'status' => true],
            ['code' => 'MX', 'dial_code' => 52, 'name' => 'Mexico', 'status' => true],
            ['code' => 'FM', 'dial_code' => 691, 'name' => 'Micronesia (Federated States of)', 'status' => true],
            ['code' => 'MD', 'dial_code' => 373, 'name' => 'Moldova, Republic of', 'status' => true],
            ['code' => 'MC', 'dial_code' => 377, 'name' => 'Monaco', 'status' => true],
            ['code' => 'MN', 'dial_code' => 976, 'name' => 'Mongolia', 'status' => true],
            ['code' => 'ME', 'dial_code' => 382, 'name' => 'Montenegro', 'status' => true],
            ['code' => 'MS', 'dial_code' => 1664, 'name' => 'Montserrat', 'status' => true],
            ['code' => 'MA', 'dial_code' => 212, 'name' => 'Morocco', 'status' => true],
            ['code' => 'MZ', 'dial_code' => 258, 'name' => 'Mozambique', 'status' => true],
            ['code' => 'MM', 'dial_code' => 95, 'name' => 'Myanmar', 'status' => true],
            ['code' => 'NA', 'dial_code' => 264, 'name' => 'Namibia', 'status' => true],
            ['code' => 'NR', 'dial_code' => 674, 'name' => 'Nauru', 'status' => true],
            ['code' => 'NP', 'dial_code' => 977, 'name' => 'Nepal', 'status' => true],
            ['code' => 'NL', 'dial_code' => 31, 'name' => 'Netherlands', 'status' => true],
            ['code' => 'NC', 'dial_code' => 687, 'name' => 'New Caledonia', 'status' => true],
            ['code' => 'NZ', 'dial_code' => 64, 'name' => 'New Zealand', 'status' => true],
            ['code' => 'NI', 'dial_code' => 505, 'name' => 'Nicaragua', 'status' => true],
            ['code' => 'NE', 'dial_code' => 227, 'name' => 'Niger', 'status' => true],
            ['code' => 'NG', 'dial_code' => 234, 'name' => 'Nigeria', 'status' => true],
            ['code' => 'NU', 'dial_code' => 683, 'name' => 'Niue', 'status' => true],
            ['code' => 'NF', 'dial_code' => 672, 'name' => 'Norfolk Island', 'status' => true],
            ['code' => 'MK', 'dial_code' => 389, 'name' => 'North Macedonia', 'status' => true],
            ['code' => 'MP', 'dial_code' => 1670, 'name' => 'Northern Mariana Islands', 'status' => true],
            ['code' => 'NO', 'dial_code' => 47, 'name' => 'Norway', 'status' => true],
            ['code' => 'OM', 'dial_code' => 968, 'name' => 'Oman', 'status' => true],
            ['code' => 'PK', 'dial_code' => 92, 'name' => 'Pakistan', 'status' => true],
            ['code' => 'PW', 'dial_code' => 680, 'name' => 'Palau', 'status' => true],
            ['code' => 'PS', 'dial_code' => 970, 'name' => 'Palestine, State of', 'status' => true],
            ['code' => 'PA', 'dial_code' => 507, 'name' => 'Panama', 'status' => true],
            ['code' => 'PG', 'dial_code' => 675, 'name' => 'Papua New Guinea', 'status' => true],
            ['code' => 'PY', 'dial_code' => 595, 'name' => 'Paraguay', 'status' => true],
            ['code' => 'PE', 'dial_code' => 51, 'name' => 'Peru', 'status' => true],
            ['code' => 'PH', 'dial_code' => 63, 'name' => 'Philippines', 'status' => true],
            ['code' => 'PN', 'dial_code' => 64, 'name' => 'Pitcairn', 'status' => true],
            ['code' => 'PL', 'dial_code' => 48, 'name' => 'Poland', 'status' => true],
            ['code' => 'PT', 'dial_code' => 351, 'name' => 'Portugal', 'status' => true],
            ['code' => 'PR', 'dial_code' => 1, 'name' => 'Puerto Rico', 'status' => true],
            ['code' => 'QA', 'dial_code' => 974, 'name' => 'Qatar', 'status' => true],
            ['code' => 'RE', 'dial_code' => 262, 'name' => 'Réunion', 'status' => true],
            ['code' => 'RO', 'dial_code' => 40, 'name' => 'Romania', 'status' => true],
            ['code' => 'RU', 'dial_code' => 7, 'name' => 'Russian Federation', 'status' => true],
            ['code' => 'RW', 'dial_code' => 250, 'name' => 'Rwanda', 'status' => true],
            ['code' => 'BL', 'dial_code' => 590, 'name' => 'Saint Barthélemy', 'status' => true],
            ['code' => 'SH', 'dial_code' => 290, 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'status' => true],
            ['code' => 'KN', 'dial_code' => 1869, 'name' => 'Saint Kitts and Nevis', 'status' => true],
            ['code' => 'LC', 'dial_code' => 1758, 'name' => 'Saint Lucia', 'status' => true],
            ['code' => 'MF', 'dial_code' => 590, 'name' => 'Saint Martin (French part)', 'status' => true],
            ['code' => 'PM', 'dial_code' => 508, 'name' => 'Saint Pierre and Miquelon', 'status' => true],
            ['code' => 'VC', 'dial_code' => 1784, 'name' => 'Saint Vincent and the Grenadines', 'status' => true],
            ['code' => 'WS', 'dial_code' => 685, 'name' => 'Samoa', 'status' => true],
            ['code' => 'SM', 'dial_code' => 378, 'name' => 'San Marino', 'status' => true],
            ['code' => 'ST', 'dial_code' => 239, 'name' => 'Sao Tome and Principe', 'status' => true],
            ['code' => 'SA', 'dial_code' => 966, 'name' => 'Saudi Arabia', 'status' => true],
            ['code' => 'SN', 'dial_code' => 221, 'name' => 'Senegal', 'status' => true],
            ['code' => 'RS', 'dial_code' => 381, 'name' => 'Serbia', 'status' => true],
            ['code' => 'SC', 'dial_code' => 248, 'name' => 'Seychelles', 'status' => true],
            ['code' => 'SL', 'dial_code' => 232, 'name' => 'Sierra Leone', 'status' => true],
            ['code' => 'SG', 'dial_code' => 65, 'name' => 'Singapore', 'status' => true],
            ['code' => 'SX', 'dial_code' => 1721, 'name' => 'Sint Maarten (Dutch part)', 'status' => true],
            ['code' => 'SK', 'dial_code' => 421, 'name' => 'Slovakia', 'status' => true],
            ['code' => 'SI', 'dial_code' => 386, 'name' => 'Slovenia', 'status' => true],
            ['code' => 'SB', 'dial_code' => 677, 'name' => 'Solomon Islands', 'status' => true],
            ['code' => 'SO', 'dial_code' => 252, 'name' => 'Somalia', 'status' => true],
            ['code' => 'ZA', 'dial_code' => 27, 'name' => 'South Africa', 'status' => true],
            ['code' => 'GS', 'dial_code' => 500, 'name' => 'South Georgia and the South Sandwich Islands', 'status' => true],
            ['code' => 'SS', 'dial_code' => 211, 'name' => 'South Sudan', 'status' => true],
            ['code' => 'ES', 'dial_code' => 34, 'name' => 'Spain', 'status' => true],
            ['code' => 'LK', 'dial_code' => 94, 'name' => 'Sri Lanka', 'status' => true],
            ['code' => 'SD', 'dial_code' => 249, 'name' => 'Sudan', 'status' => true],
            ['code' => 'SR', 'dial_code' => 597, 'name' => 'Suriname', 'status' => true],
            ['code' => 'SJ', 'dial_code' => 47, 'name' => 'Svalbard and Jan Mayen', 'status' => true],
            ['code' => 'SE', 'dial_code' => 46, 'name' => 'Sweden', 'status' => true],
            ['code' => 'CH', 'dial_code' => 41, 'name' => 'Switzerland', 'status' => true],
            ['code' => 'SY', 'dial_code' => 963, 'name' => 'Syrian Arab Republic', 'status' => true],
            ['code' => 'TW', 'dial_code' => 886, 'name' => 'Taiwan, Province of China', 'status' => true],
            ['code' => 'TJ', 'dial_code' => 992, 'name' => 'Tajikistan', 'status' => true],
            ['code' => 'TZ', 'dial_code' => 255, 'name' => 'Tanzania, United Republic of', 'status' => true],
            ['code' => 'TH', 'dial_code' => 66, 'name' => 'Thailand', 'status' => true],
            ['code' => 'TL', 'dial_code' => 670, 'name' => 'Timor-Leste', 'status' => true],
            ['code' => 'TG', 'dial_code' => 228, 'name' => 'Togo', 'status' => true],
            ['code' => 'TK', 'dial_code' => 690, 'name' => 'Tokelau', 'status' => true],
            ['code' => 'TO', 'dial_code' => 676, 'name' => 'Tonga', 'status' => true],
            ['code' => 'TT', 'dial_code' => 1868, 'name' => 'Trinidad and Tobago', 'status' => true],
            ['code' => 'TN', 'dial_code' => 216, 'name' => 'Tunisia', 'status' => true],
            ['code' => 'TR', 'dial_code' => 90, 'name' => 'Turkey', 'status' => true],
            ['code' => 'TM', 'dial_code' => 993, 'name' => 'Turkmenistan', 'status' => true],
            ['code' => 'TC', 'dial_code' => 1649, 'name' => 'Turks and Caicos Islands', 'status' => true],
            ['code' => 'TV', 'dial_code' => 688, 'name' => 'Tuvalu', 'status' => true],
            ['code' => 'UG', 'dial_code' => 256, 'name' => 'Uganda', 'status' => true],
            ['code' => 'UA', 'dial_code' => 380, 'name' => 'Ukraine', 'status' => true],
            ['code' => 'AE', 'dial_code' => 971, 'name' => 'United Arab Emirates', 'status' => true],
            ['code' => 'GB', 'dial_code' => 44, 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'status' => true],
            ['code' => 'US', 'dial_code' => 1, 'name' => 'United States of America', 'status' => true],
            ['code' => 'UM', 'dial_code' => 1, 'name' => 'United States Minor Outlying Islands', 'status' => true],
            ['code' => 'UY', 'dial_code' => 598, 'name' => 'Uruguay', 'status' => true],
            ['code' => 'UZ', 'dial_code' => 998, 'name' => 'Uzbekistan', 'status' => true],
            ['code' => 'VU', 'dial_code' => 678, 'name' => 'Vanuatu', 'status' => true],
            ['code' => 'VE', 'dial_code' => 58, 'name' => 'Venezuela (Bolivarian Republic of)', 'status' => true],
            ['code' => 'VN', 'dial_code' => 84, 'name' => 'Viet Nam', 'status' => true],
            ['code' => 'WF', 'dial_code' => 681, 'name' => 'Wallis and Futuna', 'status' => true],
            ['code' => 'EH', 'dial_code' => 212, 'name' => 'Western Sahara', 'status' => true],
            ['code' => 'YE', 'dial_code' => 967, 'name' => 'Yemen', 'status' => true],
            ['code' => 'ZM', 'dial_code' => 260, 'name' => 'Zambia', 'status' => true],
            ['code' => 'ZW', 'dial_code' => 263, 'name' => 'Zimbabwe', 'status' => true],

        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
        }
    }
}
