<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['code' => 'AFG', 'name' => 'Afghanistan', 'status' => true],
            ['code' => 'ALA', 'name' => 'Åland Islands', 'status' => true],
            ['code' => 'ALB', 'name' => 'Albania', 'status' => true],
            ['code' => 'DZA', 'name' => 'Algeria', 'status' => true],
            ['code' => 'ASM', 'name' => 'American Samoa', 'status' => true],
            ['code' => 'VIR', 'name' => 'Virgin Islands (U. S.)', 'status' => true],
            ['code' => 'AND', 'name' => 'Andorra', 'status' => true],
            ['code' => 'AGO', 'name' => 'Angola', 'status' => true],
            ['code' => 'AIA', 'name' => 'Anguilla', 'status' => true],
            ['code' => 'ATA', 'name' => 'Antarctica', 'status' => true],
            ['code' => 'ATG', 'name' => 'Antigua and Barbuda', 'status' => true],
            ['code' => 'ARG', 'name' => 'Argentina', 'status' => true],
            ['code' => 'ARM', 'name' => 'Armenia', 'status' => true],
            ['code' => 'ABW', 'name' => 'Aruba', 'status' => true],
            ['code' => 'AUS', 'name' => 'Australia', 'status' => true],
            ['code' => 'AZE', 'name' => 'Azerbaijan', 'status' => true],
            ['code' => 'BHS', 'name' => 'Bahamas (the)', 'status' => true],
            ['code' => 'BHR', 'name' => 'Bahrain', 'status' => true],
            ['code' => 'BGD', 'name' => 'Bangladesh', 'status' => true],
            ['code' => 'BRB', 'name' => 'Barbados', 'status' => true],
            ['code' => 'BEL', 'name' => 'Belgium', 'status' => true],
            ['code' => 'BLZ', 'name' => 'Belize', 'status' => true],
            ['code' => 'BLR', 'name' => 'Belarus', 'status' => true],
            ['code' => 'BEN', 'name' => 'Benin', 'status' => true],
            ['code' => 'BMU', 'name' => 'Bermuda', 'status' => true],
            ['code' => 'BTN', 'name' => 'Bhutan', 'status' => true],
            ['code' => 'BOL', 'name' => 'Bolivia', 'status' => true],
            ['code' => 'BES', 'name' => 'Bonaire', 'status' => true],
            ['code' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'status' => true],
            ['code' => 'BWA', 'name' => 'Botswana', 'status' => true],
            ['code' => 'BVT', 'name' => 'Bouvet Island', 'status' => true],
            ['code' => 'BRA', 'name' => 'Brazil', 'status' => true],
            ['code' => 'IOT', 'name' => 'British Indian Ocean Territory (the)', 'status' => true],
            ['code' => 'VGB', 'name' => 'Virgin Islands (British)', 'status' => true],
            ['code' => 'BRN', 'name' => 'Brunei Darussalam', 'status' => true],
            ['code' => 'BGR', 'name' => 'Bulgaria', 'status' => true],
            ['code' => 'BFA', 'name' => 'Burkina Faso', 'status' => true],
            ['code' => 'BDI', 'name' => 'Burundi', 'status' => true],
            ['code' => 'COK', 'name' => 'Cook Islands (the)', 'status' => true],
            ['code' => 'CUW', 'name' => 'Curaçao', 'status' => true],
            ['code' => 'TCD', 'name' => 'Chad', 'status' => true],
            ['code' => 'MNE', 'name' => 'Montenegro', 'status' => true],
            ['code' => 'CZE', 'name' => 'Czechia', 'status' => true],
            ['code' => 'CHN', 'name' => 'China', 'status' => true],
            ['code' => 'DNK', 'name' => 'Denmark', 'status' => true],
            ['code' => 'COD', 'name' => 'Congo (the Democratic Republic of the)', 'status' => true],
            ['code' => 'DMA', 'name' => 'Dominica', 'status' => true],
            ['code' => 'DOM', 'name' => 'Dominican Republic (the)', 'status' => true],
            ['code' => 'DJI', 'name' => 'Djibouti', 'status' => true],
            ['code' => 'EGY', 'name' => 'Egypt', 'status' => true],
            ['code' => 'ECU', 'name' => 'Ecuador', 'status' => true],
            ['code' => 'ERI', 'name' => 'Eritrea', 'status' => true],
            ['code' => 'EST', 'name' => 'Estonia', 'status' => true],
            ['code' => 'ETH', 'name' => 'Ethiopia', 'status' => true],
            ['code' => 'FRO', 'name' => 'Faroe Islands (the)', 'status' => true],
            ['code' => 'FLK', 'name' => 'Falklands Islands (the) [Malvinas]', 'status' => true],
            ['code' => 'FJI', 'name' => 'Fiji', 'status' => true],
            ['code' => 'PHL', 'name' => 'Philippines (the)', 'status' => true],
            ['code' => 'FIN', 'name' => 'Finland', 'status' => true],
            ['code' => 'FRA', 'name' => 'France', 'status' => true],
            ['code' => 'GUF', 'name' => 'French Guiana', 'status' => true],
            ['code' => 'ATF', 'name' => 'French Southern Territories (the)', 'status' => true],
            ['code' => 'PYF', 'name' => 'French Polynesia', 'status' => true],
            ['code' => 'GAB', 'name' => 'Gabon', 'status' => true],
            ['code' => 'GMB', 'name' => 'Gambia (the)', 'status' => true],
            ['code' => 'GHA', 'name' => 'Ghana', 'status' => true],
            ['code' => 'GIB', 'name' => 'Gibraltar', 'status' => true],
            ['code' => 'GRD', 'name' => 'Grenada', 'status' => true],
            ['code' => 'GRL', 'name' => 'Greenland', 'status' => true],
            ['code' => 'GEO', 'name' => 'Georgia', 'status' => true],
            ['code' => 'GLP', 'name' => 'Guadeloupe', 'status' => true],
            ['code' => 'GUM', 'name' => 'Guam', 'status' => true],
            ['code' => 'GTM', 'name' => 'Guatemala', 'status' => true],
            ['code' => 'GGY', 'name' => 'Guernsey', 'status' => true],
            ['code' => 'GIN', 'name' => 'Guinea', 'status' => true],
            ['code' => 'GNB', 'name' => 'Guinea-Bissau', 'status' => true],
            ['code' => 'GUY', 'name' => 'Guyana', 'status' => true],
            ['code' => 'HTI', 'name' => 'Haiti', 'status' => true],
            ['code' => 'HMD', 'name' => 'Heard Island and McDonald Islands', 'status' => true],
            ['code' => 'HND', 'name' => 'Honduras', 'status' => true],
            ['code' => 'HKG', 'name' => 'Hong Kong', 'status' => true],
            ['code' => 'CHL', 'name' => 'Chile', 'status' => true],
            ['code' => 'HRV', 'name' => 'Croatia', 'status' => true],
            ['code' => 'IND', 'name' => 'India', 'status' => true],
            ['code' => 'IDN', 'name' => 'Indonesia', 'status' => true],
            ['code' => 'IRQ', 'name' => 'Iraq', 'status' => true],
            ['code' => 'IRN', 'name' => 'Iran (Islamic Republic of)', 'status' => true],
            ['code' => 'IRL', 'name' => 'Ireland', 'status' => true],
            ['code' => 'ISL', 'name' => 'Iceland', 'status' => true],
            ['code' => 'ITA', 'name' => 'Italy', 'status' => true],
            ['code' => 'ISR', 'name' => 'Israel', 'status' => true],
            ['code' => 'JAM', 'name' => 'Jamaica', 'status' => true],
            ['code' => 'JPN', 'name' => 'Japan', 'status' => true],
            ['code' => 'YEM', 'name' => 'Yemen', 'status' => true],
            ['code' => 'JEY', 'name' => 'Jersey', 'status' => true],
            ['code' => 'ZAF', 'name' => 'South Africa', 'status' => true],
            ['code' => 'SGS', 'name' => 'South Georgia and the South Sandwich Islands', 'status' => true],
            ['code' => 'SSD', 'name' => 'South Sudan', 'status' => true],
            ['code' => 'JOR', 'name' => 'Jordan', 'status' => true],
            ['code' => 'CYM', 'name' => 'Cayman Islands (the)', 'status' => true],
            ['code' => 'KHM', 'name' => 'Cambodia', 'status' => true],
            ['code' => 'CMR', 'name' => 'Cameroon', 'status' => true],
            ['code' => 'CAN', 'name' => 'Canada', 'status' => true],
            ['code' => 'CPV', 'name' => 'Cabo Verde', 'status' => true],
            ['code' => 'QAT', 'name' => 'Qatar', 'status' => true],
            ['code' => 'KAZ', 'name' => 'Kazakhstan', 'status' => true],
            ['code' => 'KEN', 'name' => 'Kenya', 'status' => true],
            ['code' => 'KIR', 'name' => 'Kiribati', 'status' => true],
            ['code' => 'CCK', 'name' => 'Cocos (Keeling) Islands (the)', 'status' => true],
            ['code' => 'COL', 'name' => 'Colombia', 'status' => true],
            ['code' => 'COM', 'name' => 'Comoros (the)', 'status' => true],
            ['code' => 'COG', 'name' => 'Congo (the)', 'status' => true],
            ['code' => 'PRK', 'name' => "Korea (the Democratic People's Republic of)", 'status' => true],
            ['code' => 'KOR', 'name' => 'Korea (the Republic of)', 'status' => true],
            ['code' => 'XXK', 'name' => 'Kosovo', 'status' => true],
            ['code' => 'CRI', 'name' => 'Costa Rica', 'status' => true],
            ['code' => 'CUB', 'name' => 'Cuba', 'status' => true],
            ['code' => 'KWT', 'name' => 'Kuwait', 'status' => true],
            ['code' => 'CYP', 'name' => 'Cyprus', 'status' => true],
            ['code' => 'KGZ', 'name' => 'Kyrgyzstan', 'status' => true],
            ['code' => 'LAO', 'name' => "Lao People's Democratic Republic (the)", 'status' => true],
            ['code' => 'LSO', 'name' => 'Lesotho', 'status' => true],
            ['code' => 'LBN', 'name' => 'Lebanon', 'status' => true],
            ['code' => 'LBR', 'name' => 'Liberia', 'status' => true],
            ['code' => 'LBY', 'name' => 'Libya', 'status' => true],
            ['code' => 'LIE', 'name' => 'Liechtenstein', 'status' => true],
            ['code' => 'LTU', 'name' => 'Lithuania', 'status' => true],
            ['code' => 'LVA', 'name' => 'Latvia', 'status' => true],
            ['code' => 'LUX', 'name' => 'Luxembourg', 'status' => true],
            ['code' => 'MAC', 'name' => 'Macao', 'status' => true],
            ['code' => 'MDG', 'name' => 'Madagascar', 'status' => true],
            ['code' => 'HUN', 'name' => 'Hungary', 'status' => true],
            ['code' => 'MKD', 'name' => 'North Macedonia', 'status' => true],
            ['code' => 'MYS', 'name' => 'Malaysia', 'status' => true],
            ['code' => 'MWI', 'name' => 'Malawi', 'status' => true],
            ['code' => 'MDV', 'name' => 'Maldives', 'status' => true],
            ['code' => 'MLI', 'name' => 'Mali', 'status' => true],
            ['code' => 'MLT', 'name' => 'Malta', 'status' => true],
            ['code' => 'IMN', 'name' => 'Isle of Man', 'status' => true],
            ['code' => 'MAR', 'name' => 'Morocco', 'status' => true],
            ['code' => 'MHL', 'name' => 'Marshall Islands (the)', 'status' => true],
            ['code' => 'MTQ', 'name' => 'Martinique', 'status' => true],
            ['code' => 'MUS', 'name' => 'Mauritius', 'status' => true],
            ['code' => 'MRT', 'name' => 'Mauritania', 'status' => true],
            ['code' => 'MYT', 'name' => 'Mayotte', 'status' => true],
            ['code' => 'UMI', 'name' => 'United States Minor Outlying Islands (the)', 'status' => true],
            ['code' => 'MEX', 'name' => 'Mexico', 'status' => true],
            ['code' => 'FSM', 'name' => 'Micronesia (Federated States of)', 'status' => true],
            ['code' => 'MDA', 'name' => 'Moldova (the Republic of)', 'status' => true],
            ['code' => 'MCO', 'name' => 'Monaco', 'status' => true],
            ['code' => 'MNG', 'name' => 'Mongolia', 'status' => true],
            ['code' => 'MSR', 'name' => 'Montserrat', 'status' => true],
            ['code' => 'MOZ', 'name' => 'Mozambique', 'status' => true],
            ['code' => 'MMR', 'name' => 'Myanmar', 'status' => true],
            ['code' => 'NAM', 'name' => 'Namibia', 'status' => true],
            ['code' => 'NRU', 'name' => 'Nauru', 'status' => true],
            ['code' => 'DEU', 'name' => 'Germany', 'status' => true],
            ['code' => 'NPL', 'name' => 'Nepal', 'status' => true],
            ['code' => 'NER', 'name' => 'Niger (the)', 'status' => true],
            ['code' => 'NGA', 'name' => 'Nigeria', 'status' => true],
            ['code' => 'NIC', 'name' => 'Nicaragua', 'status' => true],
            ['code' => 'NIU', 'name' => 'Niue', 'status' => true],
            ['code' => 'NLD', 'name' => 'Netherlands (Kingdom of the)', 'status' => true],
            ['code' => 'NFK', 'name' => 'Norfolk Island', 'status' => true],
            ['code' => 'NOR', 'name' => 'Norway', 'status' => true],
            ['code' => 'NCL', 'name' => 'New Caledonia', 'status' => true],
            ['code' => 'NZL', 'name' => 'New Zealand', 'status' => true],
            ['code' => 'OMN', 'name' => 'Oman', 'status' => true],
            ['code' => 'PAK', 'name' => 'Pakistan', 'status' => true],
            ['code' => 'PLW', 'name' => 'Palau', 'status' => true],
            ['code' => 'PSE', 'name' => 'Palestine, State of', 'status' => true],
            ['code' => 'PAN', 'name' => 'Panama', 'status' => true],
            ['code' => 'PNG', 'name' => 'Papua New Guinea', 'status' => true],
            ['code' => 'PRY', 'name' => 'Paraguay', 'status' => true],
            ['code' => 'PER', 'name' => 'Peru', 'status' => true],
            ['code' => 'PCN', 'name' => 'Pitcairn', 'status' => true],
            ['code' => 'CIV', 'name' => 'Côte d\'Ivoire', 'status' => true],
            ['code' => 'POL', 'name' => 'Poland', 'status' => true],
            ['code' => 'PRI', 'name' => 'Puerto Rico', 'status' => true],
            ['code' => 'PRT', 'name' => 'Portugal', 'status' => true],
            ['code' => 'AUT', 'name' => 'Austria', 'status' => true],
            ['code' => 'REU', 'name' => 'Réunion', 'status' => true],
            ['code' => 'GNQ', 'name' => 'Equatorial Guinea', 'status' => true],
            ['code' => 'ROU', 'name' => 'Romania', 'status' => true],
            ['code' => 'RUS', 'name' => 'Russian Federation (the)', 'status' => true],
            ['code' => 'RWA', 'name' => 'Rwanda', 'status' => true],
            ['code' => 'GRC', 'name' => 'Greece', 'status' => true],
            ['code' => 'SPM', 'name' => 'Saint Pierre and Miquelon', 'status' => true],
            ['code' => 'SLV', 'name' => 'El Salvador', 'status' => true],
            ['code' => 'WSM', 'name' => 'Samoa', 'status' => true],
            ['code' => 'SMR', 'name' => 'San Marino', 'status' => true],
            ['code' => 'SAU', 'name' => 'Saudi Arabia', 'status' => true],
            ['code' => 'SEN', 'name' => 'Senegal', 'status' => true],
            ['code' => 'MNP', 'name' => 'Northern Mariana Islands (the)', 'status' => true],
            ['code' => 'SYC', 'name' => 'Seychelles', 'status' => true],
            ['code' => 'SLE', 'name' => 'Sierra Leone', 'status' => true],
            ['code' => 'SGP', 'name' => 'Singapore', 'status' => true],
            ['code' => 'SVK', 'name' => 'Slovakia', 'status' => true],
            ['code' => 'SVN', 'name' => 'Slovenia', 'status' => true],
            ['code' => 'SOM', 'name' => 'Somalia', 'status' => true],
            ['code' => 'ARE', 'name' => 'United Arab Emirates (the)', 'status' => true],
            ['code' => 'USA', 'name' => 'United States of America (the)', 'status' => true],
            ['code' => 'SRB', 'name' => 'Serbia', 'status' => true],
            ['code' => 'CAF', 'name' => 'Central African Republic (the)', 'status' => true],
            ['code' => 'SDN', 'name' => 'Sudan (the)', 'status' => true],
            ['code' => 'SUR', 'name' => 'Suriname', 'status' => true],
            ['code' => 'SHN', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'status' => true],
            ['code' => 'LCA', 'name' => 'Saint Lucia', 'status' => true],
            ['code' => 'BLM', 'name' => 'Saint Barthélemy', 'status' => true],
            ['code' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'status' => true],
            ['code' => 'MAF', 'name' => 'Saint Martin (French part)', 'status' => true],
            ['code' => 'SXM', 'name' => 'Sint Maarten (Dutch part)', 'status' => true],
            ['code' => 'STP', 'name' => 'Sao Tome and Principe', 'status' => true],
            ['code' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'status' => true],
            ['code' => 'SWZ', 'name' => 'Eswatini', 'status' => true],
            ['code' => 'SYR', 'name' => 'Syrian Arab Republic (the)', 'status' => true],
            ['code' => 'SLB', 'name' => 'Solomon Islands', 'status' => true],
            ['code' => 'ESP', 'name' => 'Spain', 'status' => true],
            ['code' => 'SJM', 'name' => 'Svalbard and Jan Mayen', 'status' => true],
            ['code' => 'LKA', 'name' => 'Sri Lanka', 'status' => true],
            ['code' => 'SWE', 'name' => 'Sweden', 'status' => true],
            ['code' => 'CHE', 'name' => 'Switzerland', 'status' => true],
            ['code' => 'TJK', 'name' => 'Tajikistan', 'status' => true],
            ['code' => 'TZA', 'name' => 'Tanzania, the United Republic of', 'status' => true],
            ['code' => 'THA', 'name' => 'Thailand', 'status' => true],
            ['code' => 'TWN', 'name' => 'Taiwan', 'status' => true],
            ['code' => 'TGO', 'name' => 'Togo', 'status' => true],
            ['code' => 'TKL', 'name' => 'Tokelau', 'status' => true],
            ['code' => 'TON', 'name' => 'Tonga', 'status' => true],
            ['code' => 'TTO', 'name' => 'Trinidad and Tobago', 'status' => true],
            ['code' => 'TUN', 'name' => 'Tunisia', 'status' => true],
            ['code' => 'TUR', 'name' => 'Türkiye', 'status' => true],
            ['code' => 'TKM', 'name' => 'Turkmenistan', 'status' => true],
            ['code' => 'TCA', 'name' => 'Turks and Caicos Islands (the)', 'status' => true],
            ['code' => 'TUV', 'name' => 'Tuvalu', 'status' => true],
            ['code' => 'UGA', 'name' => 'Uganda', 'status' => true],
            ['code' => 'UKR', 'name' => 'Ukraine', 'status' => true],
            ['code' => 'URY', 'name' => 'Uruguay', 'status' => true],
            ['code' => 'UZB', 'name' => 'Uzbekistan', 'status' => true],
            ['code' => 'CXR', 'name' => 'Christmas Island', 'status' => true],
            ['code' => 'VUT', 'name' => 'Vanuatu', 'status' => true],
            ['code' => 'VAT', 'name' => 'Holy See (the)', 'status' => true],
            ['code' => 'GBR', 'name' => 'United Kingdom of Great Britain and Northern Ireland (the)', 'status' => true],
            ['code' => 'VEN', 'name' => 'Venezuela (Bolivarian Republic of)', 'status' => true],
            ['code' => 'VNM', 'name' => 'Viet Nam', 'status' => true],
            ['code' => 'TLS', 'name' => 'Timor-Leste', 'status' => true],
            ['code' => 'WLF', 'name' => 'Wallis and Futuna', 'status' => true],
            ['code' => 'ZMB', 'name' => 'Zambia', 'status' => true],
            ['code' => 'ESH', 'name' => 'Western Sahara', 'status' => true],
            ['code' => 'ZWE', 'name' => 'Zimbabwe', 'status' => true],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
        }
    }
}
